# Generated by Django 5.0.6 on 2025-01-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregistration",
            name="high_school",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="middle_school",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
