# Generated by Django 4.2.26 on 2025-11-18 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_alter_userregistration_high_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='password',
            field=models.CharField(default='3ammak', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
